### ISSUE TITLE
What is _num_ in sql ? in class Model: findNumber()

### ISSUE THREAD

**Issue by bestplay** [michaelliao/awesome-python3-webapp#1]
感谢您的 python 教程@michaelliao。 有个疑问：

orm模块中 Model 类中定义了 findNumber() 方法。

里面的的这句 SQL：
"select %s **_num_** from `%s`"

其中 **_num_** 没有看懂。。。

我是不是错过了啥？

**Comment by rikouki** [comment]
'select count(account_id)** _num_ **from account'
'select count(account_id)** as _num_ **from account'
就是别名

**Comment by bestplay** [comment]
额。怪我， 平常用 as...
